# Generated by Django 6.0.4 on 2026-04-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='case_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='case_type',
            field=models.CharField(choices=[('ADMINISTRATIVE', 'Administrative'), ('JUDICIAL', 'Judicial'), ('LEGISLATIVE', 'Legislative')], default='ADMINISTRATIVE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_email',
            field=models.EmailField(default='xyz@yahoo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_id',
            field=models.CharField(default='C000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_name',
            field=models.CharField(default='Anonymous', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(default='Public Works', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_INFO', 'Pending Info'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.complaint')),
            ],
        ),
    ]
