# Generated by Django 6.0.4 on 2026-04-19 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complaint_case_number_complaint_case_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email must be in the format alphanumeric@xyz.com', regex='^[A-Za-z0-9]+@xyz\\.com$')])),
                ('national_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be in the format NID-123456789', regex='^NID-\\d{9}$')])),
                ('password_hash', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('OFFICER', 'Officer'), ('SENIOR_OFFICER', 'Senior Officer'), ('DEPT_HEAD', 'Department Head'), ('ADMIN', 'Administrator')], default='CITIZEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
