# Generated by Django 6.0.4 on 2026-04-19 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_portaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='national_id_type',
            field=models.CharField(choices=[('AADHAR', 'Aadhaar'), ('PAN', 'PAN')], default='AADHAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be 10 or 16 digits', regex='^(\\d{10}|\\d{16})$')]),
        ),
    ]
