# Generated by Django 6.0.4 on 2026-04-19 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portaluser_national_id_type_alter_portaluser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be 16 digits (Aadhaar) or 10 alphanumeric characters (PAN)', regex='^(\\d{16}|[A-Za-z0-9]{10})$')]),
        ),
    ]
